feat: added support for multiple cron jobs in a class
Padam87/CronBundle pull request #17
Opened 2022-08-01 11:57 UTC by dragondungeon1

Since my last update i am converting all my annotations to attributes.

Then I found a file that has 3 con jobs, so I tried to add 3 attribute cron jobs but since I forgot to add IS_REPEATABLE. 

So now i am adding it.

I will also put in a PR for the master branch.

2022-08-01 14:06 UTC, Padam87 commented
https://github.com/Padam87/CronBundle/blob/master/Tests/HelperTest.php#L64

Works just fine in the test suite.

2022-08-01 21:30 UTC, mwansinck requested changes

2022-08-01 21:30 UTC, mwansinck commented on Annotation/Job.php
> +#[\Attribute(\Attribute::IS_REPEATABLE,)]
Please remove the trailing comma's

2022-08-02 06:35 UTC, dragondungeon1 commented on Annotation/Job.php
> +#[\Attribute(\Attribute::IS_REPEATABLE,)]
check

2022-08-02 11:10 UTC, mwansinck approved these changes

2022-08-02 12:58 UTC, dragondungeon1 commented
@Padam87 
 In the PR before this you told me that ->newInstance() also could work.
 
newInstance is checking if an attribute is repeatable or not and will fail if it isnt, resulting in your current test for TwoAttributeCommand failing.

This wasn't possible earlier because of the way we handled the Annotations, but with the NamedArgumentConstructor Annotation and the followed modifications we now can use newInstance()


This is how i will be using the attributes: 
![image](https://user-images.githubusercontent.com/58809801/182375462-9a5bf923-ba79-47d9-88cd-a842c904b9b2.png)

2022-08-02 13:29 UTC, Padam87 commented
So far it passes without a problem, adding 2 jobs to the tab.

Please provide a failing test warranting the new instance change, and a new test covering the repeatable feature.

2022-08-02 13:55 UTC, dragondungeon1 commented
>  Please provide a failing test warranting the new instance change

I don't understand what you are trying to achieve here, the newInstance() method shall not fail in any way I can predict. (it will fail by removing Attribute::IS_REPEATABLE from the Job class, but this can't be achieved at runtime, because this is "coded")

>  and a new test covering the repeatable feature.

I believe the TwoAttributesCommand test is already covering this. When removing the Attribute::IS_REPEATABLE this test will then fail (because the newInstance() will fail to execute

2022-08-02 14:17 UTC, Padam87 commented
> I don't understand what you are trying to achieve here, the newInstance() method shall not fail in any way I can predict. (it will fail by removing Attribute::IS_REPEATABLE from the Job class, but this can't be achieved at runtime, because this is "coded")

You are trying to replace ->newInstance with this: https://github.com/Padam87/CronBundle/pull/17/commits/9e52580a6dc29ca73cc54fc74c1a1823e3407ba1
I don't understand why, and I asked for a failing test warranting this change.

>I believe the TwoAttributesCommand test is already covering this. When removing the Attribute::IS_REPEATABLE this test will then fail (because the newInstance() will fail to execute

The test passes without IS_REPEATABLE.
https://github.com/Padam87/CronBundle/runs/7594044255?check_suite_focus=true#step:5:12

2022-08-02 15:19 UTC, Padam87 commented
Ah, man, you didn't replace with newInstance the last time,  and this time you didn't rebase your code on top of the new one... that is what the confusion is.

Next time please don't mark it as resolved until it actually is, because I don't have the time to review every small thing.

2022-08-02 15:20 UTC, closed without merging

2022-08-03 06:39 UTC, dragondungeon1 commented
Dear Adam, thank you for bringing my changes to the codebase.

Next time will be better